'use client'

import { motion } from 'framer-motion'
import { Navbar } from '@/components/marketing/navbar'
import { Footer } from '@/components/marketing/footer'

const SECTIONS = [
  {
    title: 'Acceptance of Terms',
    content:
      "By accessing or using AI Marketing Commander ('the Platform'), operated by 4Pie Labs, you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not access or use the Platform. These terms apply to all users including beta participants, registered members, and team account holders.",
  },
  {
    title: 'Beta Program',
    content:
      'The Platform is currently in beta. Access is invite-only and granted at our sole discretion. Beta features may change, be limited, or be discontinued without prior notice. Beta access does not guarantee continued access post-launch or any specific pricing.',
  },
  {
    title: 'Account Responsibilities',
    content:
      'You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized account access. One account per individual unless a Team plan is active. You must not share login credentials or invite links with unauthorized parties.',
  },
  {
    title: 'Acceptable Use',
    content:
      'You agree not to use the Platform to: generate content that is illegal, harmful, or violates third-party rights; attempt to reverse-engineer or extract our underlying AI prompts or systems; resell or redistribute platform outputs without attribution; overload our systems through automated scraping or bulk API abuse; or impersonate other users or entities.',
  },
  {
    title: 'AI-Generated Content',
    content:
      'Content generated by the Platform is produced using third-party AI models. We do not guarantee the accuracy, originality, or fitness of AI-generated outputs for any specific purpose. You are solely responsible for reviewing, editing, and ensuring the appropriateness of all content before publishing or delivering it to clients.',
  },
  {
    title: 'Intellectual Property',
    content:
      'You retain ownership of content you create using the Platform. 4Pie Labs retains ownership of the Platform itself, including its design, code, workflows, and proprietary systems. You grant us a limited license to process your inputs solely to provide the service.',
  },
  {
    title: 'Payments & Billing',
    content:
      'Paid plans will be introduced following the beta period. Beta users who qualify for founding member pricing will be notified separately. All payments will be processed securely via Stripe. Refund policies will be published alongside paid plan launch details.',
  },
  {
    title: 'Limitation of Liability',
    content:
      'To the maximum extent permitted by law, 4Pie Labs shall not be liable for indirect, incidental, special, or consequential damages arising from your use of the Platform. Our total liability shall not exceed the amount paid by you in the three months preceding the claim.',
  },
  {
    title: 'Termination',
    content:
      'We reserve the right to suspend or terminate your account at any time for violation of these terms or for any other reason at our discretion. Upon termination, your right to access the Platform ceases immediately.',
  },
  {
    title: 'Changes to Terms',
    content:
      'We may update these Terms at any time. Registered users will be notified of material changes via email. Continued use of the Platform after changes constitutes acceptance.',
  },
  {
    title: 'Contact & Governing Law',
    content:
      'These Terms are governed by the laws applicable to 4Pie Labs. For questions, contact us at legal@fourpielabs.com or visit fourpielabs.com.',
  },
]

export default function TermsPage() {
  return (
    <>
      <Navbar />

      {/* Hero Header */}
      <div
        className="legal-hero"
        style={{
          background: '#080B14',
          paddingTop: '120px',
          paddingBottom: '80px',
          textAlign: 'center',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        <div
          style={{
            position: 'absolute',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            width: '600px',
            height: '300px',
            borderRadius: '50%',
            background: 'radial-gradient(ellipse, rgba(37,99,235,0.12) 0%, transparent 70%)',
            pointerEvents: 'none',
          }}
        />
        <div
          className="font-[family-name:var(--font-syne)]"
          style={{
            position: 'relative',
            display: 'inline-block',
            fontSize: '11px',
            letterSpacing: '3px',
            color: '#2563EB',
            fontWeight: 600,
            textTransform: 'uppercase' as const,
            marginBottom: '16px',
          }}
        >
          Legal
        </div>
        <h1
          className="font-[family-name:var(--font-syne)]"
          style={{
            fontSize: 'clamp(32px, 5vw, 52px)',
            fontWeight: 800,
            color: '#ffffff',
            margin: '0 0 16px',
            lineHeight: 1.1,
          }}
        >
          Terms of Service
        </h1>
        <p
          className="font-[family-name:var(--font-dm-sans)]"
          style={{
            fontSize: '14px',
            color: '#475569',
          }}
        >
          Last updated: March 10, 2026
        </p>
      </div>

      {/* Content Area */}
      <div
        className="legal-content"
        style={{
          background: 'var(--mk-bg-secondary)',
          minHeight: '60vh',
        }}
      >
        <div
          style={{
            maxWidth: '780px',
            margin: '0 auto',
            padding: '80px 40px',
          }}
        >
          {SECTIONS.map((section) => (
            <motion.section
              key={section.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4 }}
              style={{ marginBottom: '48px' }}
            >
              <h2
                className="font-[family-name:var(--font-syne)]"
                style={{
                  fontSize: '20px',
                  fontWeight: 700,
                  color: 'var(--mk-text-primary)',
                  marginBottom: '16px',
                  paddingBottom: '12px',
                  borderBottom: '1px solid var(--mk-border)',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '10px',
                }}
              >
                <span
                  style={{
                    width: '4px',
                    height: '20px',
                    borderRadius: '2px',
                    background: 'linear-gradient(180deg, #2563EB, #06B6D4)',
                    display: 'inline-block',
                    flexShrink: 0,
                  }}
                />
                {section.title}
              </h2>
              <p
                className="font-[family-name:var(--font-dm-sans)]"
                style={{
                  fontSize: '15px',
                  color: 'var(--mk-text-secondary)',
                  lineHeight: 1.8,
                  marginBottom: '12px',
                }}
              >
                {section.content}
              </p>
            </motion.section>
          ))}
        </div>
      </div>

      <Footer />
    </>
  )
}